version: "3.8"

services:
  sb-app:
    image: yosrbou449/test2:latest
    build: .
    container_name: "mongo-demo"
    ports:
      - 9090:9090
    networks:
      - mynetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb-service"
    ports:
      - "27070:27017"
    volumes:
      - /home:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge




#version: "3.8"
#services:
#  sb-app:
#    build: .
#    container_name: "mongo-demo"
#    ports:
#      - 9090:9090
#  mongodb:
#    image: mongo:latest
#    container_name: "mongodb"
#    ports:
#      - 27070:27017
